import './globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'My first next project',
  description: 'Generated by create next app',
}

const links = [{
  label: "Home",
  route: "/"
}, {
  label: "About",
  route: "/about"
}]

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <title>My first Next.js App</title> */}
      <body>
        <header>
          <nav>
            <ul>
              {links.map(({ label, route }) => {
                return <li key={route}>
                  <Link href={route}>
                    {label}
                  </Link>
                </li>
              })}
            </ul>
          </nav>
        </header>
        <div>
          {children}
        </div>
      </body>
    </html>
  )
}
